### ISSUE TITLE
Oracle control quits unexpectedly before visualizing anything

### ISSUE THREAD

**Issue by eglassman** [serenabooth/Interfaces_for_HCRL#4]
`(env) MacBook-Pro-2:Interfaces_for_HCRL elenaleah$ python3 Domains/cartpole_oracle.py

Best reward: 201.0
[-0.45921958 -1.70265461 -0.42931037 -0.34886277]
p to play, q to quit
p
0

2020-04-03 08:57:06.778 Python[2147:47593] ApplePersistenceIgnoreState: Existing state will not be touched. New state will be written to (null)

Traceback (most recent call last):
  File "Domains/cartpole_oracle.py", line 235, in <module>
    save_trajectory(domain, trained_params)
  File "Domains/cartpole_oracle.py", line 186, in save_trajectory
    reward, done = env.take_action(action, record=True)
  File "/Users/elenaleah/GitRepos/Interfaces_for_HCRL/Domains/cartpole.py", line 140, in take_action
    self.save_screenshot("tmp/" + str(self.screenshot_count) + ".png")
  File "/Users/elenaleah/GitRepos/Interfaces_for_HCRL/Domains/cartpole.py", line 160, in save_screenshot
    pyglet.image.get_buffer_manager().get_color_buffer().save('Screenshots/' + filename)
  File "/Users/elenaleah/GitRepos/Interfaces_for_HCRL/env/lib/python3.7/site-packages/pyglet/image/__init__.py", line 489, in save
    file = open(filename, 'wb')
FileNotFoundError: [Errno 2] No such file or directory: 'Screenshots/tmp/1.png'
Exception ignored in: <function Viewer.__del__ at 0x120156830>
Traceback (most recent call last):
  File "/Users/elenaleah/GitRepos/Interfaces_for_HCRL/env/lib/python3.7/site-packages/gym/envs/classic_control/rendering.py", line 152, in __del__
  File "/Users/elenaleah/GitRepos/Interfaces_for_HCRL/env/lib/python3.7/site-packages/gym/envs/classic_control/rendering.py", line 71, in close
  File "/Users/elenaleah/GitRepos/Interfaces_for_HCRL/env/lib/python3.7/site-packages/pyglet/window/cocoa/__init__.py", line 277, in close
  File "/Users/elenaleah/GitRepos/Interfaces_for_HCRL/env/lib/python3.7/site-packages/pyglet/window/__init__.py", line 820, in close

ImportError: sys.meta_path is None, Python is likely shutting down`

**Comment by eglassman** [comment]
Looks like it needs a file to already exist that doesn't: 
`file = open(filename, 'wb')
FileNotFoundError: [Errno 2] No such file or directory: 'Screenshots/tmp/1.png'`

**Comment by eglassman** [comment]
@serenabooth do you want to check that the file & directory exists first, and create it if it doesn't?
